name: alquranalkareem
description: Al-Quran Al-Kareem - Al-Heekmah Library.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.2.6+46

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  anim_search_bar: ^2.0.3
  animated_toggle_switch: ^0.8.0
  another_xlider: ^3.0.2
  arabic_numbers: ^1.0.0
  bot_toast: ^4.1.3
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  day_night_time_picker: ^1.3.0+1
  desktop_window: ^0.4.0
  dio: ^5.4.0
  easy_image_viewer: ^1.3.2
  equatable: ^2.0.5
  expansion_tile_card: ^3.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_sliding_box: ^1.1.5
  flutter_sliding_up_panel: ^2.1.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  flutter_timezone: ^1.0.8
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^7.6.4
  glob: ^2.1.2
  group_button: ^5.3.3
  hijri: ^3.0.0
#  home_widget: ^0.4.1
  html: ^0.15.4
  interactive_slider: ^0.2.2
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  lottie: ^2.7.0
  mini_music_visualizer: ^1.0.2
  package_rename: ^1.5.2
  path: ^1.8.3
  path_provider: ^2.1.1
  quiver: ^3.2.1
  rate_my_app: ^2.0.0
  responsive_builder: ^0.7.0
  rxdart: ^0.27.7
  screenshot: ^2.1.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.1
  square_percent_indicater: ^0.1.0
  url_launcher: ^6.2.2
  wakelock_plus: ^1.1.4
  webview_flutter: ^4.4.4
  workmanager: ^0.5.2
#  audio_service: ^0.18.12
#  scroll_to_index: ^3.0.1


dev_dependencies:
  build_runner: ^2.4.7
  flutter_native_splash: ^2.3.8
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#f3efdf"
  color_dark: "#2d2d2d"
  image: assets/app_icon.png
  image_dark: assets/app_icon.png

  android_12:
    image: assets/app_icon.png
    icon_background_color: "#f3efdf"
    image_dark: assets/app_icon.png
    icon_background_color_dark: "#2d2d2d"

package_rename_config:
  android:
    package_name: com.alheekmah.alquranalkareem.alquranalkareem

  ios:
    app_name: القرآن الكريم - مكتبة الحكمة
    package_name: com.alheekmah.alquranalkareem.alquranalkareem

    macos:
      app_name: القرآن الكريم مكتبة الحكمة
      package_name: com.alheekmah.alquranalkareem.alquranalkareem2

  flutter_lints: ^3.0.1

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/surah_name/
    - assets/svg/juz/
    - assets/onboarding/
    - assets/images/
    - assets/svg/hijri/
    - assets/svg/alwaqf/
    - assets/svg/quarter/
    - assets/json/
    - assets/json/translate/
    - assets/lottie/
    - assets/locales/
    - assets/share_images/
    - assets/share_images/surah_name/
    - assets/QuranV3.sqlite
    - assets/baghawyV2.db
    - assets/ibnkatheerV2.sqlite
    - assets/qurtubiV2.db
    - assets/tabariV2.db
    - assets/saadiV2.db
    - assets/ayahinfo_1260.db
    - assets/app_icon.png
    - assets/json/azkar.json

  fonts:
    - family: uthmanic
      fonts:
        - asset: assets/fonts/UthmanTN1_Ver10.otf

    - family: uthmanic2
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf

    - family: kufi
      fonts:
        - asset: assets/fonts/Kufam-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Kufam-VariableFont_wght.ttf
          weight: 500
        - asset: assets/fonts/Kufam-Regular.ttf
          weight: 100

    - family: naskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf

    - family: urdu
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu.ttf

    - family: bn
      fonts:
        - asset: assets/fonts/NotoSerifBengali.ttf

    - family: hafs1
      fonts:
        - asset: assets/fonts/quran_fonts/p2001.ttf
    - family: hafs2
      fonts:
        - asset: assets/fonts/quran_fonts/p2002.ttf
    - family: hafs3
      fonts:
        - asset: assets/fonts/quran_fonts/p2003.ttf
    - family: hafs4
      fonts:
        - asset: assets/fonts/quran_fonts/p2004.ttf
    - family: hafs5
      fonts:
        - asset: assets/fonts/quran_fonts/p2005.ttf
